"""Focused cold-process + real Host + formal MCP nonseparable vertical.

Reuses only transport startup/client infrastructure from the font contract.
The independent fixed PNG byte expectations are not generated by the kernel.
"""
import argparse
import copy
import json
from pathlib import Path
import struct
import subprocess
import tempfile
import zlib
import font_mcp_parity as transport

MODES = ['hue', 'saturation', 'color', 'luminosity']
IDS = ['normal','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion'] + MODES + ['linear-burn','linear-dodge','linear-light','vivid-light','pin-light','hard-mix','subtract','divide','darker-color','lighter-color']
ORACLE = [(105,80,122,255),(41,104,168,255),(122,71,122,255),(56,107,158,255)]
CHECKS = 0

def png_rgba(path):
    """Decode the Qt fixture using stdlib, independently of the blend renderer.

    Only noninterlaced 8-bit RGB/RGBA is needed. Check chunk CRCs and reverse
    all five PNG scanline filters; unexpected formats fail explicitly.
    """
    data = path.read_bytes()
    assert data[:8] == b'\x89PNG\r\n\x1a\n', 'PNG signature'
    offset, header, compressed, ended = 8, None, bytearray(), False
    while offset < len(data):
        assert offset + 12 <= len(data), 'Truncated PNG chunk'
        length, kind = struct.unpack_from('>I4s', data, offset)
        end = offset + 12 + length
        assert end <= len(data), 'Truncated PNG payload'
        payload = data[offset+8:end-4]
        crc, = struct.unpack_from('>I', data, end-4)
        assert zlib.crc32(kind+payload) & 0xffffffff == crc, 'PNG chunk CRC'
        if kind == b'IHDR':
            assert header is None and offset == 8 and length == 13, 'PNG header'
            header = struct.unpack('>IIBBBBB', payload)
        elif kind == b'IDAT':
            assert header is not None, 'PNG data before header'
            compressed.extend(payload)
        elif kind == b'IEND':
            assert length == 0 and end == len(data), 'PNG end'
            ended = True
            break
        else:
            assert kind != b'tRNS', 'PNG color-key transparency is unsupported'
            assert kind[0] & 32, 'Unexpected critical PNG chunk'
        offset = end
    assert header is not None and compressed and ended, 'Incomplete PNG'
    width, height, depth, color, compression, filtering, interlace = header
    assert 0 < width <= 4096 and 0 < height <= 4096, 'Bounded PNG fixture dimensions'
    assert depth == 8 and color in (2, 6) and (compression, filtering, interlace) == (0, 0, 0), 'Unsupported PNG fixture format'
    channels = 3 if color == 2 else 4
    stride = width * channels
    raw = zlib.decompress(compressed)
    assert len(raw) == height * (stride+1), 'PNG scanline length'
    previous, pixels = bytearray(stride), bytearray()
    for y in range(height):
        start = y * (stride+1)
        filter_type = raw[start]
        assert filter_type <= 4, 'PNG scanline filter'
        row = bytearray(raw[start+1:start+1+stride])
        for x in range(stride):
            left = row[x-channels] if x >= channels else 0
            above = previous[x]
            upper_left = previous[x-channels] if x >= channels else 0
            prediction = left + above - upper_left
            pa, pb, pc = abs(prediction-left), abs(prediction-above), abs(prediction-upper_left)
            paeth = left if pa <= pb and pa <= pc else above if pb <= pc else upper_left
            row[x] = (row[x] + (0, left, above, (left+above)//2, paeth)[filter_type]) & 255
        if channels == 4:
            pixels.extend(row)
        else:
            for x in range(0, stride, channels):
                pixels.extend(row[x:x+3]); pixels.append(255)
        previous = row
    return (width, height), bytes(pixels)


def check(value, why):
    global CHECKS
    if not value:
        raise AssertionError(why)
    CHECKS += 1

def rectangle(id_, x, y, w, h, color):
    return dict(id=id_, name=id_, kind='path', visible=True,
        compositing=dict(version=1, opacity=dict(literal=1), blend='normal', isolated=False, mask=None),
        transform=[dict(literal=v) for v in [1,0,0,1,0,0]],
        anchor=[dict(literal=0), dict(literal=0)], transform_parent=None,
        contours=[dict(id=id_+'-contour', closed=True, points=[dict(id=id_+'-p'+str(i),
            x=dict(literal=px), y=dict(literal=py), in_angle=dict(literal=0), in_length=dict(literal=0),
            out_angle=dict(literal=0), out_length=dict(literal=0))
            for i,(px,py) in enumerate([(x,y),(x+w,y),(x+w,y+h),(x,y+h)])])],
        stack=[dict(kind='operation', operation=dict(id=id_+'-fill', type='nect.paint.fill',
            version=1, enabled=True, parameters={channel:dict(literal=value/255)
                for channel,value in zip(('r','g','b','a'),color)}, composite='below', fill_rule='nonzero'))],
        legacy_stroke='')

def native_fixture(client):
    native = client.snapshot()
    board = native['compositions'][0]['artboards'][0]
    board.update(x=0,y=0,width=64,height=64)
    native['objects'] = [rectangle('backdrop',0,0,64,64,(51,102,153,255))] + [
        rectangle(mode,8+32*(i%2),8+32*(i//2),16,16,(204,51,102,255)) for i,mode in enumerate(MODES)]
    native['compositions'][0]['roots'] = [o['id'] for o in native['objects']]
    native['objects'].sort(key=lambda o:o['id'])
    return native

def static_discovery():
    # Only protocol/discovery and unchanged forwarding are proved here. No
    # socket, desktop-session integration, pixels or cold reopen is inferred.
    client=transport.Client('unused-blend-discovery-endpoint')
    try:
        client.initialize()
        tools=client.rpc('tools/list')['tools']
        description=next(t for t in tools if t['name']=='nect_command')['description']
        for token in ('Hue','Saturation','Color','Luminosity','native 0.79','UNSUPPORTED_BLEND_PROFILE',
                      'Qt raster','16/32-bpc','unverified AE','per-mode descriptors/arithmetic'):
            check(token in description,'Missing truthful MCP discovery: '+token)
    finally:
        transport.stop(client.proc)
    import io
    import sys
    import mcp_server as server
    calls=[]
    def record(endpoint,envelope):
        calls.append((endpoint,envelope))
        return dict(ok=False,error=dict(code='UNSUPPORTED_BLEND_PROFILE',message='test-only forwarding sentinel'))
    incoming=[dict(jsonrpc='2.0',id=1,method='initialize',params=dict(protocolVersion='2025-06-18',capabilities={},clientInfo=dict(name='blend-static',version='1'))),
              dict(jsonrpc='2.0',method='notifications/initialized')]
    for i,mode in enumerate(MODES):
        incoming.append(dict(jsonrpc='2.0',id=i+2,method='tools/call',params=dict(name='nect_command',
            arguments=dict(session_id='test-session',document_id='test-document',request=dict(op='apply',expected_revision=3,
                commands=[dict(type='set_compositing',object='target',blend=mode,isolated=False,profile='unavailable-profile')])))))
    output=io.BytesIO()
    original=(sys.stdin,sys.stdout,server.call)
    try:
        sys.stdin=io.TextIOWrapper(io.BytesIO(('\n'.join(map(json.dumps,incoming))+'\n').encode()))
        sys.stdout=io.TextIOWrapper(output)
        server.call=record
        server.run('test-only-static-endpoint')
        sys.stdout.flush()
        replies=[json.loads(line) for line in output.getvalue().splitlines()]
    finally:
        sys.stdin,sys.stdout,server.call=original
    check(len(calls)==4 and len(replies)==5,'Four unchanged formal-MCP forwarding calls')
    for i,mode in enumerate(MODES):
        endpoint,envelope=calls[i]
        check(endpoint=='test-only-static-endpoint' and envelope==dict(op='core',session_id='test-session',document_id='test-document',
              request=dict(op='apply',expected_revision=3,commands=[dict(type='set_compositing',object='target',blend=mode,isolated=False,profile='unavailable-profile')])),
              'Formal MCP forwards exact ID/profile/revision to existing Host envelope')
        result=replies[i+1]['result']
        check(result['isError'] and result['structuredContent']['error']['code']=='UNSUPPORTED_BLEND_PROFILE' and
              json.loads(result['content'][0]['text'])==result['structuredContent'],'Formal MCP preserves canonical failure truth')
    print(json.dumps(dict(status='PASS',checks=CHECKS,transport_checks=transport.CHECKS,
        evidence='protocol/discovery/static-forwarding-only',live_desktop_ipc=False)))

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('desktop',nargs='?')
    parser.add_argument('cli',nargs='?')
    parser.add_argument('--discovery-only',action='store_true')
    args=parser.parse_args()
    if args.discovery_only:
        static_discovery()
        return
    if not args.desktop or not args.cli:
        parser.error("desktop and CLI executable paths are required for live IPC validation")
    desktop=client=None
    with tempfile.TemporaryDirectory(prefix='nect-blend-vertical-') as tmp:
        directory=Path(tmp)
        try:
            desktop,client=transport.start(str(Path(args.desktop).resolve()),directory,'initial')
            client.initialize()
            live=client.refresh()
            tools=client.rpc('tools/list')['tools']
            description=next(t for t in tools if t['name']=='nect_command')['description']
            for token in ('Hue','Saturation','Color','Luminosity','native 0.79','UNSUPPORTED_BLEND_PROFILE','Qt raster','16/32-bpc','unverified AE'):
                check(token in description,'Missing truthful MCP discovery: '+token)
            types=client.compare('compositing_types')['result']
            check(types['blends']==IDS,'Exact immutable16-ID discovery')
            check([d['id'] for d in types['blend_descriptors']]==IDS,'Descriptor discovery order')
            check(types['production_profile']=='nect.srgb8-premultiplied/v1' and
                  all(d['ae_oracle_status']=='unverified' for d in types['blend_descriptors']), 'Current profile and AE status')
            check(all(not p['supported'] for p in types['unavailable_profiles']),'Unavailable profile cells explicit')
            native=native_fixture(client)
            initial=directory/'initial.nect'
            initial.write_text(json.dumps(native))
            opened=client.tool('nect_file',dict(client.identity,op='open',path=str(initial),expected_revision=live['revision']))
            check(opened['ok'],opened)
            live=client.refresh()
            check(client.snapshot()==native,'Prepared native source opens exactly')
            comp=native['compositions'][0]['id'];board=native['compositions'][0]['artboards'][0]['id']
            revision=0
            for mode in MODES:
                before=client.snapshot()
                command=dict(type='set_compositing',object=mode,blend=mode,isolated=False,profile=types['production_profile'])
                result=client.core('apply',expected_revision=revision,commands=[command,
                    dict(type='set',ref=dict(object=mode,point='',field='composite.opacity'),value=.5)])
                check(result['ok'] and result['revision']==revision+1,result)
                authored=client.snapshot()
                check(next(o for o in authored['objects'] if o['id']==mode)['compositing']['blend']==mode,'MCP stores exact mode ID')
                undone=client.core('undo',expected_revision=result['revision'])
                check(undone['ok'] and client.snapshot()==before,'MCP Undo exact')
                redone=client.core('redo',expected_revision=undone['revision'])
                check(redone['ok'] and client.snapshot()==authored,'MCP Redo exact')
                revision=redone['revision']
                readback=client.compare('compositing_plan',composition=comp)
                check(any(n['blend']==mode and n['isolated'] for n in readback['result']['roots']), 'MCP/API scope readback')
                # SetCompositing retains the established accepted-same-value
                # revision behavior. Both transports must preserve exact intent
                # and advance once, rather than inventing a no-op contract.
                replay=client.direct(dict(op='apply',expected_revision=revision,commands=[command]))
                check(replay['ok'] and replay['revision']==revision+1 and client.snapshot()==authored,
                    'Direct API same-value command preserves intent and advances one revision')
                revision=replay['revision']
                mcp_replay=client.core('apply',expected_revision=revision,commands=[command])
                check(mcp_replay==dict(replay,revision=revision+1) and client.snapshot()==authored,
                    'MCP same-value command matches direct API response and authored intent')
                revision=mcp_replay['revision']
            retained=client.snapshot();history=client.compare('history');identity=dict(client.identity)
            for mode in ('Hue','colour','future-mode'):
                bad=client.core('apply',expected_revision=revision,commands=[dict(type='set_compositing',object='hue',blend=mode,isolated=False)])
                check(not bad['ok'] and bad['error']['code']=='UNSUPPORTED_BLEND',bad)
            bad=client.core('apply',expected_revision=revision,commands=[dict(type='set_compositing',object='hue',blend='hue',isolated=False,profile='linear-srgb16')])
            check(not bad['ok'] and bad['error']['code']=='UNSUPPORTED_BLEND_PROFILE',bad)
            stale=client.core('apply',expected_revision=revision-1,commands=[dict(type='set_compositing',object='hue',blend='normal',isolated=False)])
            check(not stale['ok'] and stale['error']['code']=='REVISION_CONFLICT',stale)
            check(client.snapshot()==retained and client.compare('history')==history,'Unknown/profile/stale failures atomic')
            for mode in MODES:
                lie=copy.deepcopy(retained)
                lie['version']='0.78'
                for obj in lie['objects']:
                    if obj['id'] in MODES and obj['id']!=mode:
                        obj['compositing']['blend']='normal'
                path=directory/(mode+'-078-lie.nect');path.write_text(json.dumps(lie))
                rejection=client.tool('nect_file',dict(client.identity,op='open',path=str(path),expected_revision=revision))
                check(not rejection['ok'] and rejection['error']['code']=='NATIVE_VERSION_MISMATCH',rejection)
                check(client.snapshot()==retained and client.identity==identity and client.refresh()['revision']==revision and client.compare('history')==history,'Old-version lie preserves live Session/history/identity')
                cold=subprocess.run([str(Path(args.cli).resolve()),'--validate'],input=json.dumps(lie),text=True,capture_output=True)
                check(cold.returncode==2 and 'NATIVE_VERSION_MISMATCH' in cold.stderr,'Cold CLI exact0.78 lie refusal')
            plan=client.compare('export_plan',composition=comp,artboard=board)['result']
            check(plan['svg_export_supported'] and not plan['cross_reader_pixel_identity'] and
                  not plan['nect_svg_blend_intake_supported'] and [d['id'] for d in plan['blend_capabilities']]==IDS,'Descriptor-owned SVG target capability')
            svg=client.compare('export_svg',composition=comp,artboard=board)['result']
            # export_svg result may wrap text; normalize only transport shape.
            if isinstance(svg,dict):
                svg=svg['svg']
            for mode in MODES:
                check('mix-blend-mode:'+mode in svg and 'isolation:isolate' in svg,'SVG exactID/isolation')
            png=directory/'all-four.png'
            result=client.tool('nect_export_png',dict(client.identity,op='export_png',expected_revision=revision,
                path=str(png),composition=comp,artboard=board,scale=1,background='transparent'))
            check(result['ok'],result)
            size,pixels=png_rgba(png)
            check(size==(64,64),'MCP PNG dimensions')
            for i,expected in enumerate(ORACLE):
                offset=((16+32*(i//2))*size[0]+16+32*(i%2))*4
                check(tuple(pixels[offset:offset+4])==expected,'MCP decoded independent PNG oracle '+MODES[i])
            analysis=client.tool('nect_analyze_regions',dict(client.identity,op='analyze_regions',expected_revision=revision,
                composition=comp,artboard=board,scale=1,threshold=1))
            check(analysis['ok'],analysis)
            check(client.snapshot()==retained,'PNG and region analysis preserve native source')
            saved=directory/'all-four.nect'
            result=client.tool('nect_file',dict(client.identity,op='save',path=str(saved),expected_revision=revision))
            check(result['ok'] and json.loads(saved.read_text())==retained,'MCP saves exact current0.80 native')
            cold=subprocess.run([str(Path(args.cli).resolve()),'--normalize'],input=saved.read_text(),text=True,capture_output=True)
            check(cold.returncode==0 and json.loads(cold.stdout)==retained,'Separate CLI cold native reopen equality')
            transport.stop(client.proc);client=None;transport.stop(desktop);desktop=None
            desktop,client=transport.start(str(Path(args.desktop).resolve()),directory,'cold',saved)
            client.initialize();live=client.refresh()
            check(live['revision']==0 and client.identity!=identity and client.snapshot()==retained,'Separate desktop process cold reopen equality')
            stale=client.tool('nect_command',dict(identity,request=dict(op='apply',expected_revision=0,commands=[dict(type='set_compositing',object='hue',blend='normal',isolated=False)])))
            check(not stale['ok'] and stale['error']['code']=='SESSION_CONFLICT' and client.snapshot()==retained,'Old Session identity cannot edit cold reopen')
            print(json.dumps(dict(status='PASS',checks=CHECKS,transport_checks=transport.CHECKS,native_version='0.80',
                modes=MODES,desktop_processes=2,formal_mcp=True,api_parity=True,cold_native=True,
                old_version_lies='four separate live and cold rejections',png_oracle=True,ae_parity='unverified',
                gui_acceptance=False,windows_consumer_acceptance=False),sort_keys=True))
        finally:
            if client: transport.stop(client.proc)
            transport.stop(desktop)

if __name__=='__main__': main()
