#include "window.hpp"
#include "inherited_grid_alignment_fixture.hpp"
#include <QApplication>
#include <QAction>
#include <QLineEdit>
#include <QListWidget>
#include <QPushButton>
#include <QSettings>
#include <QStatusBar>
#include <QTemporaryDir>
#include <QFile>
#include <QProcess>
#include <QTest>
#include <iostream>
#include <stdexcept>
using namespace nect;
using namespace nect::desktop;
namespace {
int checks=0;
void check(bool ok,const char*why){if(!ok)throw std::runtime_error(why);++checks;}
void events(){QApplication::processEvents();}
Document fixture(){auto d=inherited_grid_fixture::document();d.compositions.front().artboards.front().layout->margin=Margin{10,20,30,40};return d;}
const Artboard& board(const Document&d,const Id&id="A"){for(const auto&b:d.compositions.front().artboards)if(b.id==id)return b;throw std::runtime_error("missing Artboard");}
Artboard effective(const Document&d,const Id&id="A"){return evaluate_artboard(d.compositions.front(),id);}
template<class T>T* control(Window&w,const char*name){for(auto*p:w.findChildren<T*>(name))if(p->isVisible())return p;throw std::runtime_error(std::string("missing control ")+name);}
void edit(Window&w,const QString&id="A"){
 auto* list=w.findChild<QListWidget*>("artboards");check(list,"Artboard list available");bool found=false;for(int i=0;i<list->count();++i)if(list->item(i)->data(Qt::UserRole+1).toString()==id){list->setCurrentItem(list->item(i));found=true;break;}check(found,"stable target selected");events();control<QPushButton>(w,"artboard-edit")->click();events();
}
void click(Window&w,const char*name){auto*p=control<QPushButton>(w,name);check(p->isEnabled(),"public action enabled");p->click();events();}
void value(Window&w,const char*name,const QString&v){control<QLineEdit>(w,name)->setText(v);}
void history(Window&w,const QString&name){for(auto*a:w.findChildren<QAction*>())if(a->text()==name){a->trigger();events();return;}throw std::runtime_error("missing History action");}
void load(Window&w,Document d=fixture()){w.canvas->cancel_interaction();w.host.session=Session(std::move(d));w.refresh();events();edit(w);}
void reset(Window&w,const std::string&field){w.host.session.apply({ArtboardTemplateCommand{ResetArtboardTemplateOverride{"comp","A",field}}},w.host.session.revision());w.host.edited();events();edit(w);}
}
int main(int argc,char**argv){qputenv("QT_QPA_PLATFORM","offscreen");QApplication app(argc,argv);try{
 check(argc==2,"core CLI path required");QTemporaryDir dir;check(dir.isValid(),"owned scratch available");QSettings settings(dir.filePath("library.ini"),QSettings::IniFormat);Window w(dir.path(),std::make_unique<FolderLibrary>(settings));w.show();events();load(w);
 check(control<QLineEdit>(w,"margin-left")->text().toDouble()==10&&control<QLineEdit>(w,"margin-bottom")->text().toDouble()==40,"inherited Margin shown as evaluated insets");
 check(control<QLineEdit>(w,"grid-x")->text().toDouble()==40&&control<QLineEdit>(w,"grid-width")->text().toDouble()==100,"inherited Grid shown as evaluated bounds");
 const auto original=encode(w.host.session.document());value(w,"margin-left","15");click(w,"margin-apply");auto applied=encode(w.host.session.document());
 check(board(w.host.session.document()).template_assignment->margin_overridden&&!board(w.host.session.document()).template_assignment->grid_overridden,"Margin Apply overrides only Margin");check(effective(w.host.session.document()).layout->margin->left==15&&effective(w.host.session.document()).layout->grid->bounds.x==40,"Margin edit preserves inherited Grid");history(w,"Undo");check(encode(w.host.session.document())==original,"Undo restores exact original inheritance");history(w,"Redo");check(encode(w.host.session.document())==applied,"Redo restores exact family override");
 auto source=board(w.host.session.document(),"source");source.layout->grid->bounds.x=70;w.host.session.apply({SetArtboardLayout{"comp","source",source.layout}},w.host.session.revision());w.host.edited();events();check(effective(w.host.session.document()).layout->grid->bounds.x==70&&effective(w.host.session.document()).layout->margin->left==15,"source Grid remains live after local Margin edit");
 load(w);const auto grid_id=board(w.host.session.document()).template_assignment->grid_id;value(w,"grid-x","55");click(w,"grid-apply");check(board(w.host.session.document()).template_assignment->grid_overridden&&!board(w.host.session.document()).template_assignment->margin_overridden,"Grid Apply overrides only Grid");check(board(w.host.session.document()).layout->grid->id==grid_id&&effective(w.host.session.document()).layout->grid->bounds.x==55,"Grid Apply retains target-local stable identity");
 load(w);click(w,"margin-clear");check(!effective(w.host.session.document()).layout->margin&&effective(w.host.session.document()).layout->grid.has_value()&&!board(w.host.session.document()).template_assignment->grid_overridden,"Clear inherited Margin suppresses only Margin");reset(w,"layout.margin");check(effective(w.host.session.document()).layout->margin->left==10,"Reset restores inherited Margin");
 load(w);click(w,"grid-clear");check(!effective(w.host.session.document()).layout->grid&&effective(w.host.session.document()).layout->margin.has_value()&&!board(w.host.session.document()).template_assignment->margin_overridden,"Clear inherited Grid suppresses only Grid");reset(w,"layout.grid");check(effective(w.host.session.document()).layout->grid->bounds.x==40,"Reset restores inherited Grid");
 load(w);click(w,"grid-copy-margin-box");const auto copied=effective(w.host.session.document());check(copied.layout->grid->bounds==LayoutRect{10,20,copied.width-40,copied.height-60},"copy inherited Margin box has exact local bounds");check(!board(w.host.session.document()).template_assignment->margin_overridden&&board(w.host.session.document()).layout->grid->id==grid_id,"copy changes only Grid with stable ID");source=board(w.host.session.document(),"source");source.layout->margin->left=25;w.host.session.apply({SetArtboardLayout{"comp","source",source.layout}},w.host.session.revision());w.host.edited();events();check(effective(w.host.session.document()).layout->margin->left==25&&effective(w.host.session.document()).layout->grid->bounds.x==10,"copy is one-shot while inherited Margin keeps following");

 load(w);{const auto before=encode(w.host.session.document());auto* input=control<QLineEdit>(w,"margin-left");input->selectAll();QTest::keyClicks(input,"17");events();check(encode(w.host.session.document())==before&&w.host.session.gesture_active(),"typing previews without committing");check(effective(w.host.session.preview_document()).layout->margin->left==17&&!board(w.host.session.preview_document()).template_assignment->grid_overridden,"preview is family-local");click(w,"margin-left-cancel");check(encode(w.host.session.document())==before&&!w.host.session.gesture_active()&&w.host.session.revision()==0,"Cancel preserves bytes and History");}
 load(w);{auto* stale=control<QPushButton>(w,"margin-apply");value(w,"margin-left","88");w.host.session.apply({ArtboardTemplateCommand{SetArtboardTemplateOverride{"comp","A","layout.margin",std::optional<Margin>{Margin{19,20,30,40}}}}},w.host.session.revision());const auto newer=encode(w.host.session.document());stale->click();events();check(encode(w.host.session.document())==newer&&w.statusBar()->currentMessage().contains("REVISION_CONFLICT"),"stale captured revision refuses overwrite");}
 load(w);{auto* stale=control<QPushButton>(w,"grid-apply");value(w,"grid-x","88");const auto before=encode(w.host.session.document());w.host.session_id+="-replacement";stale->click();events();check(encode(w.host.session.document())==before&&w.host.session.revision()==0,"stale Session identity refuses commit");}
 {auto d=fixture();auto& src=d.compositions.front().artboards.front();src.layout->margin->left_expression=Expression{"12",1};src.layout->grid->columns=2;src.layout->grid->column_gutter=3;src.layout->grid->bounds_x_expression=Expression{"45",1};load(w,d);check(control<QLineEdit>(w,"margin-left")->text().toDouble()==12&&control<QLineEdit>(w,"grid-x")->text().toDouble()==45,"inherited driven source displays evaluated values");value(w,"margin-top","21");click(w,"margin-apply");check(!board(w.host.session.document()).layout->margin->left_expression&&board(w.host.session.document()).layout->margin->left==12,"new Margin override does not clone inherited driver");edit(w);click(w,"grid-copy-margin-box");const auto& grid=*board(w.host.session.document()).layout->grid;check(!grid.bounds_x_expression&&grid.columns==2&&grid.column_gutter==3,"copy inherited Grid retains counts/gutters without source metadata");check(board(w.host.session.document(),"source")==src,"inherited source authored record unchanged");}
 {auto d=fixture();auto& target=d.compositions.front().artboards[1];target.layout=ArtboardLayout{Margin{10,20,30,40},{}};target.template_assignment->margin_overridden=true;target.layout->margin->left_expression=Expression{R"(ref("source","","artboard.width") * 0 + 12)",1};load(w,d);check(control<QLineEdit>(w,"margin-left")->isReadOnly(),"local driven Margin remains read-only");value(w,"margin-top","22");click(w,"margin-apply");check(board(w.host.session.document()).layout->margin->left_expression==target.layout->margin->left_expression&&!board(w.host.session.document()).template_assignment->grid_overridden,"local Margin source preserved without overriding Grid");edit(w);const auto before=encode(w.host.session.document());click(w,"margin-clear");check(encode(w.host.session.document())==before&&!w.host.session.gesture_active()&&w.statusBar()->currentMessage().contains("DRIVEN_"),"driven Margin Clear rejected atomically");}
 {auto d=fixture();auto& target=d.compositions.front().artboards[1];auto grid=*d.compositions.front().artboards.front().layout->grid;grid.id=target.template_assignment->grid_id;grid.bounds_x_expression=Expression{R"(ref("source","","artboard.width") * 0 + 45)",1};target.layout=ArtboardLayout{{},grid};target.template_assignment->grid_overridden=true;load(w,d);check(control<QLineEdit>(w,"grid-x")->isReadOnly(),"local driven Grid remains read-only");value(w,"grid-y","35");click(w,"grid-apply");check(board(w.host.session.document()).layout->grid->bounds_x_expression==grid.bounds_x_expression&&!board(w.host.session.document()).template_assignment->margin_overridden,"local Grid source preserved without overriding Margin");edit(w);const auto before=encode(w.host.session.document());click(w,"grid-clear");check(encode(w.host.session.document())==before&&w.statusBar()->currentMessage().contains("DRIVEN_"),"driven Grid Clear rejected atomically");edit(w);click(w,"grid-copy-margin-box");check(encode(w.host.session.document())==before,"copy refuses replacement of driven local bounds");}
 {auto d=fixture();auto& target=d.compositions.front().artboards[1];target.template_assignment.reset();target.layout=ArtboardLayout{Margin{1,2,3,4},Grid{"plain-grid",{5,6,70,80},1,1,0,0}};load(w,d);value(w,"margin-left","9");click(w,"margin-apply");check(board(w.host.session.document()).layout->grid->id=="plain-grid"&&!board(w.host.session.document()).template_assignment&&board(w.host.session.document()).layout->margin->left==9,"plain-Artboard family edit behavior unchanged");}
 load(w);click(w,"grid-copy-margin-box");

 load(w);click(w,"grid-clear");edit(w);value(w,"grid-x","5");value(w,"grid-width","100");click(w,"grid-apply");check(board(w.host.session.document()).layout->grid->id==grid_id&&effective(w.host.session.document()).layout->grid->bounds.x==5&&!board(w.host.session.document()).template_assignment->margin_overridden,"Apply after suppressed Grid uses assignment identity and preserves Margin inheritance");
 load(w);{const auto before=encode(w.host.session.document());auto* input=control<QLineEdit>(w,"grid-x");input->selectAll();QTest::keyClicks(input,"66");events();check(w.host.session.gesture_active()&&encode(w.host.session.document())==before,"Grid preview leaves committed state unchanged");click(w,"grid-bounds-x-cancel");check(encode(w.host.session.document())==before&&!w.host.session.gesture_active(),"Grid Cancel discards actual Session preview");}
 load(w);click(w,"grid-copy-margin-box");

 for(const auto* name:{"margin-clear","grid-clear"}){load(w);auto* stale=control<QPushButton>(w,name);w.host.session=Session(empty_document("new-document","new-comp","new-frame"));w.host.session_id+="-new";const auto replacement=encode(w.host.session.document());stale->click();events();check(encode(w.host.session.document())==replacement&&w.host.session.revision()==0,"stale Clear after replaced document refuses without lookup exception");}
 load(w);click(w,"grid-copy-margin-box");

 load(w);{auto* input=control<QLineEdit>(w,"margin-left");input->selectAll();QTest::keyClicks(input,"18");events();auto* stale=control<QPushButton>(w,"margin-apply");w.host.session.cancel_gesture();w.host.session.apply({ArtboardTemplateCommand{SetArtboardTemplateOverride{"comp","A","layout.margin",std::optional<Margin>{Margin{23,20,30,40}}}}},w.host.session.revision());const auto newer=encode(w.host.session.document());stale->click();events();check(encode(w.host.session.document())==newer&&!w.host.session.gesture_active(),"stale active preview cannot overwrite newer committed revision");}
 load(w);{const auto before=encode(w.host.session.document());auto* input=control<QLineEdit>(w,"grid-width");input->selectAll();QTest::keyClicks(input,"-1");events();click(w,"grid-apply");check(encode(w.host.session.document())==before&&w.host.session.revision()==0,"invalid Grid draft cannot commit earlier valid preview");click(w,"grid-bounds-width-cancel");check(!w.host.session.gesture_active()&&encode(w.host.session.document())==before,"Cancel clears invalid draft safely");}
 load(w);click(w,"grid-copy-margin-box");
 const auto file=dir.filePath("layout.nect");w.host.save(file);QFile saved(file);check(saved.open(QIODevice::ReadOnly),"Host native saved");const auto bytes=saved.readAll();check(bytes.toStdString()==encode(w.host.session.document()),"saved exact authored bytes");QProcess cold;cold.start(QString::fromLocal8Bit(argv[1]),QStringList{"--validate"});check(cold.waitForStarted(5000),"cold process starts");cold.write(bytes);cold.closeWriteChannel();check(cold.waitForFinished(10000)&&cold.exitCode()==0&&cold.exitStatus()==QProcess::NormalExit,"cold native validation passes");
 std::cout<<"PASS "<<checks<<" Template layout Window/Host checks\n";return 0;
 }catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
